[package]
name = "hydrogen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.48"

[lib]
name = "hydrogen"
path = "src/lib.rs"

[[bin]]
name = "hydrogen"
path = "src/main.rs"
